version: "3"
services:
  bot:
    restart: unless-stopped
    container_name: bot
    image: containers.pkg.github.com/Webeleon/discord-bot-starter
    env_file:
      - .env
  mongo:
    container_name: mongodb
    image: mongo:4.4
    env_file:
      - .env
